"""
CLI module - backward compatibility wrapper.

This module re-exports all functionality from the cli/ package.
For new code, prefer importing directly from letterboxd_rec.cli.
"""

# Re-export everything from the cli package for backward compatibility
from .cli import (
    main,
    setup_jam_parser,
    # Commands
    cmd_scrape,
    cmd_scrape_social,
    cmd_backfill_social,
    cmd_scrape_daemon,
    cmd_discover,
    cmd_discover_refill,
    cmd_discover_from_taste,
    cmd_recommend,
    cmd_similar_users,
    cmd_jam,
    cmd_stats,
    cmd_export,
    cmd_import,
    cmd_refresh_metadata,
    cmd_queue_status,
    cmd_queue_add,
    cmd_queue_clear,
    cmd_prune_pending,
    cmd_session_history,
    cmd_explore,
    cmd_profile,
    cmd_similar,
    cmd_triage,
    cmd_svd_info,
    cmd_gaps,
    cmd_rebuild_idf,
    # Utilities (backward compat)
    send_notification,
    _require_slug,
    _validate_slug,
    _validate_username,
    _parse_weights,
    _load_all_user_films,
    _load_films_with_filters,
    _load_recommendation_data,
    _warn_missing_metadata,
    _scrape_film_metadata,
    _persist_metadata_batch,
    _scrape_film_metadata_async,
    _scrape_users_parallel,
    _run_metadata_strategy,
    _run_collaborative_strategy,
    _run_hybrid_strategy,
    _run_graph_strategy,
    _run_svd_strategy,
    _output_recommendations,
)

__all__ = [
    'main',
    'setup_jam_parser',
    'cmd_scrape',
    'cmd_scrape_social',
    'cmd_backfill_social',
    'cmd_scrape_daemon',
    'cmd_discover',
    'cmd_discover_refill',
    'cmd_discover_from_taste',
    'cmd_recommend',
    'cmd_similar_users',
    'cmd_jam',
    'cmd_stats',
    'cmd_export',
    'cmd_import',
    'cmd_refresh_metadata',
    'cmd_queue_status',
    'cmd_queue_add',
    'cmd_queue_clear',
    'cmd_prune_pending',
    'cmd_session_history',
    'cmd_explore',
    'cmd_profile',
    'cmd_similar',
    'cmd_triage',
    'cmd_svd_info',
    'cmd_gaps',
    'cmd_rebuild_idf',
    'send_notification',
    '_require_slug',
    '_validate_slug',
    '_validate_username',
    '_parse_weights',
    '_load_all_user_films',
    '_load_films_with_filters',
    '_load_recommendation_data',
    '_warn_missing_metadata',
    '_scrape_film_metadata',
    '_persist_metadata_batch',
    '_scrape_film_metadata_async',
    '_scrape_users_parallel',
    '_run_metadata_strategy',
    '_run_collaborative_strategy',
    '_run_hybrid_strategy',
    '_run_graph_strategy',
    '_run_svd_strategy',
    '_output_recommendations',
]
